// <auto-generated />
using System;
using FitFood.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitFood.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420123316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitFood.API.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("FitFood.API.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "вул. Богдана Гаврилишина, 24 (1 поверх)",
                            Categories = "[\"\\u041A\\u0430\\u0432\\u0430\",\"\\u0412\\u0438\\u043F\\u0456\\u0447\\u043A\\u0430\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\",\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\"]",
                            ImageUrl = "/images/restaurants/bufet.jpg",
                            MapImageUrl = "/images/maps/map_bufet.jpg",
                            Name = "Буфет",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Берестейський просп., 24",
                            Categories = "[\"\\u0424\\u0430\\u0441\\u0442\\u0444\\u0443\\u0434\",\"\\u041A\\u0443\\u0440\\u043A\\u0430\",\"\\u0411\\u0443\\u0440\\u0433\\u0435\\u0440\\u0438\",\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\"]",
                            ImageUrl = "/images/restaurants/kfc.jpg",
                            MapImageUrl = "/images/maps/map_kfc.jng",
                            Name = "KFC",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "вул. Богдана Гаврилишина, 12/16",
                            Categories = "[\"\\u0423\\u043A\\u0440\\u0430\\u0457\\u043D\\u0441\\u044C\\u043A\\u0430 \\u043A\\u0443\\u0445\\u043D\\u044F\",\"\\u0414\\u043E\\u043C\\u0430\\u0448\\u043D\\u0456 \\u0441\\u0442\\u0440\\u0430\\u0432\\u0438\",\"\\u041E\\u0431\\u0456\\u0434\"]",
                            ImageUrl = "/images/restaurants/nadecudogadzi.jpg",
                            MapImageUrl = "/images/maps/map_nadecudogadzi.jpg",
                            Name = "На-децу-до-газди",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Берестейський просп., 24 (Smart Plaza)",
                            Categories = "[\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\",\"\\u0428\\u0430\\u0443\\u0440\\u043C\\u0430\",\"\\u0424\\u0430\\u0441\\u0442\\u0444\\u0443\\u0434\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\"]",
                            ImageUrl = "/images/restaurants/greekhouse.jpg",
                            MapImageUrl = "/images/maps/map_greekhouse.jpg",
                            Name = "Greek House",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 5,
                            Address = "вул. Богдана Гаврилишина, 7",
                            Categories = "[\"\\u042F\\u043F\\u043E\\u043D\\u0441\\u044C\\u043A\\u0430 \\u043A\\u0443\\u0445\\u043D\\u044F\",\"\\u0420\\u043E\\u043B\\u0438\",\"\\u0421\\u0443\\u0448\\u0456\",\"\\u041E\\u0431\\u0456\\u0434\"]",
                            ImageUrl = "/images/restaurants/menyamusashi.jpg",
                            MapImageUrl = "/images/maps/map_menyamusashi.jpg",
                            Name = "Мenya Musashi",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Address = "вул. Політехнічна (Смарт Плаза)",
                            Categories = "[\"\\u0423\\u043A\\u0440\\u0430\\u0457\\u043D\\u0441\\u044C\\u043A\\u0430 \\u043A\\u0443\\u0445\\u043D\\u044F\",\"\\u041E\\u0431\\u0456\\u0434\",\"\\u0414\\u043E\\u043C\\u0430\\u0448\\u043D\\u0456 \\u0441\\u0442\\u0440\\u0430\\u0432\\u0438\"]",
                            ImageUrl = "/images/restaurants/puzata_hata.jpg",
                            MapImageUrl = "/images/maps/map_puzata.jpg",
                            Name = "Пузата Хата",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 7,
                            Address = "Берестейський просп., 24",
                            Categories = "[\"\\u042F\\u043F\\u043E\\u043D\\u0441\\u044C\\u043A\\u0430 \\u043A\\u0443\\u0445\\u043D\\u044F\",\"\\u0421\\u0443\\u0448\\u0456\",\"\\u0420\\u043E\\u043B\\u0438\",\"\\u041E\\u0431\\u0456\\u0434\"]",
                            ImageUrl = "/images/restaurants/sushiya.jpg",
                            MapImageUrl = "/images/maps/map_sushiya.jpg",
                            Name = "Сушія",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 8,
                            Address = "вул. Довженка, 1",
                            Categories = "[\"\\u0411\\u0443\\u0440\\u0433\\u0435\\u0440\\u0438\",\"\\u0424\\u0430\\u0441\\u0442\\u0444\\u0443\\u0434\",\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\"]",
                            ImageUrl = "/images/restaurants/yudginburger.jpg",
                            MapImageUrl = "/images/maps/map_yudginburger.jpg",
                            Name = "Юджин Бургер",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 9,
                            Address = "ст. м. Політехнічний інститут",
                            Categories = "[\"\\u0412\\u0438\\u043F\\u0456\\u0447\\u043A\\u0430\",\"\\u041A\\u0430\\u0432\\u0430\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\",\"\\u041D\\u0430\\u043F\\u043E\\u0457\"]",
                            ImageUrl = "/images/restaurants/lvivcroissants.jpg",
                            MapImageUrl = "/images/maps/map_lvivcroissants.jpg",
                            Name = "Львівські Круасани",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 10,
                            Address = "вул. Богдана Гаврилишина, 6",
                            Categories = "[\"\\u041D\\u0430\\u043F\\u043E\\u0457\",\"\\u0417\\u0430\\u043A\\u0443\\u0441\\u043A\\u0438\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\"]",
                            ImageUrl = "/images/restaurants/hop_hey.jpg",
                            MapImageUrl = "/images/maps/map_hop_hey.jpg",
                            Name = "Hop Hey",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 11,
                            Address = "вул. Богдана Гаврилишина, 6",
                            Categories = "[\"\\u041A\\u0430\\u0432\\u0430\",\"\\u0412\\u0438\\u043F\\u0456\\u0447\\u043A\\u0430\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\",\"\\u041D\\u0430\\u043F\\u043E\\u0457\"]",
                            ImageUrl = "/images/restaurants/talk.jpg",
                            MapImageUrl = "/images/maps/map_talk.jpg",
                            Name = "TALK (кав'ярня)",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 12,
                            Address = "вул. Богдана Гаврилишина, 3",
                            Categories = "[\"\\u041A\\u0430\\u0432\\u0430\",\"\\u0412\\u0438\\u043F\\u0456\\u0447\\u043A\\u0430\",\"\\u041D\\u0430\\u043F\\u043E\\u0457\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\"]",
                            ImageUrl = "/images/restaurants/coffee_gang.jpg",
                            MapImageUrl = "/images/maps/map_coffee_gang.jpg",
                            Name = "Coffee Gang",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 13,
                            Address = "Берестейський просп., 24",
                            Categories = "[\"\\u0428\\u0430\\u0443\\u0440\\u043C\\u0430\",\"\\u0424\\u0430\\u0441\\u0442\\u0444\\u0443\\u0434\",\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\",\"\\u041A\\u0443\\u0440\\u043A\\u0430\"]",
                            ImageUrl = "/images/restaurants/doner.png",
                            MapImageUrl = "/images/maps/map_doner.jpg",
                            Name = "Doner Маркет",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 14,
                            Address = "Берестейський просп., 32",
                            Categories = "[\"\\u0411\\u0443\\u0440\\u0433\\u0435\\u0440\\u0438\",\"\\u0424\\u0430\\u0441\\u0442\\u0444\\u0443\\u0434\",\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\",\"\\u041D\\u0430\\u043F\\u043E\\u0457\"]",
                            ImageUrl = "/images/restaurants/mcdonalds.jpg",
                            MapImageUrl = "/images/maps/map_mcdonalds.jpg",
                            Name = "McDonald's",
                            Rating = 3.8999999999999999
                        },
                        new
                        {
                            Id = 15,
                            Address = "Берестейський просп., 26А",
                            Categories = "[\"\\u0428\\u0430\\u0443\\u0440\\u043C\\u0430\",\"\\u0424\\u0430\\u0441\\u0442\\u0444\\u0443\\u0434\",\"\\u041F\\u0435\\u0440\\u0435\\u043A\\u0443\\u0441\",\"\\u0428\\u0432\\u0438\\u0434\\u043A\\u0435 \\u0445\\u0430\\u0440\\u0447\\u0443\\u0432\\u0430\\u043D\\u043D\\u044F\"]",
                            ImageUrl = "/images/restaurants/vah_shaurma.jpg",
                            MapImageUrl = "/images/maps/map_vah_shaurma.jpg",
                            Name = "Vah Shaurma",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("FitFood.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FitFood.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
